version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: amazondb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "8090:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      retries: 5
    restart: always