#spring.datasource.driverClassName=org.postgresql.Driver
#spring.datasource.url=jdbc:postgresql://localhost:5432/amazondb
#spring.datasource.username=postgres
#spring.datasource.password=root
#spring.jpa.hibernate.ddl-auto=create


spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/amazondb
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

management.endpoint.metrics.enabled=true
management.endpoints.web.exposure.include=*
management.endpoints.metrics.enabled=true
management.endpoint.prometheus.enabled=true